version: "3"

services:
    fuadmin-mysql-dev:
        image: mysql:8
        container_name: fuadmin-mysql-dev
        restart: always
        ports:
            - 33060:3306
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "fuadmin"
            TZ: Asia/Shanghai
        volumes:
            - mysql:/var/lib/mysql

    fuadmin-redis-dev:
        image: redis:7-alpine
        container_name: fuadmin-redis-dev
        restart: on-failure
        environment:
            - TZ=Asia/Shanghai
        ports:
            - 63790:6379
        expose:
            - 6379
        volumes:
            - redis:/data

volumes:
    mysql:
    redis:

